title: blog.glenux.net
description: Chroniques d'un gnou libre

gems:
 - jekyll-paginate
 - jekyll-mentions
 - jekyll-sitemap
 - jekyll-feed

url: http://blog.glenux.net
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: 360° of tech
   url: /category/360-of-tech/
 - title: Contact
   url: /contact/

social:
   github: glenux
   twitter: glenux
   facebook: glenux
   email: glenux@glenux.net

google_analytics: ""

